# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

php:
  - 7.0

script: phpunit --configuration phpunit.xml tests/

#notifications:
#  irc: "irc.freenode.org#phpwomen"
